### ISSUE TITLE
👋

### ISSUE THREAD

**Issue by wooorm** [itgalaxy/remark-preset-lint-itgalaxy#19]
Hi!

I just wanted to ping and see if you’ve got any further questions regarding the changes in remark.
Your changes looks good (I only think [`remark-comment-config` on L8](https://github.com/itgalaxy/remark-preset-lint-itgalaxy/blob/e705fa557ae488a035ba281cc099e1a98d2fe489/index.js#L8) isn’t needed)
Could you let me know below or on [Gitter](https://gitter.im/wooorm/remark) if you’ve got any questions?

**Comment by evilebottnawi** [comment]
@wooorm oh, thanks you are right :smile: all works fine after upgrade, thanks for quickly reply

**Comment by wooorm** [comment]
Alright, great!
